### ISSUE TITLE
Vnet option

### ISSUE THREAD

**Issue by ramaswin121994** [Azure-Samples/ansible-playbooks#44]
https://github.com/Azure-Samples/ansible-playbooks/blob/946dc2b7d686ec9679e40a2ca4c0a7af79cf15b3/aks_create_scale.yml#

How can I add exist Vnet id

**Comment by yuwzho** [comment]
Hi @ramaswin121994 Do you mean attach the existing vnet to the AKS? I don't think AKS service api supports this operation according to the [documentation](https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate)

If you mention the ventSubnetID in the [AgentPollProfile](https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#managedclusteragentpoolprofile), you can set the agent_poll_profile like

```yml
      agent_pool_profiles:
        - name: default
          count: 3
          vm_size: Standard_D2_v2
          vnet_subnet_id: "your vnet subnet id"
```
