### ISSUE TITLE
Unsupported framework dotnetcore for Windows web app.

### ISSUE THREAD

**Issue by bloudman** [Azure-Samples/ansible-playbooks#75]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
run this playboook
```yaml
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: "{{ lookup('env', 'RES_GROUP') }}"
    webapp_name: "{{ lookup('env', 'WEB_APP_NAME') }}"
    location: eastus
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
    - name: Create a dotnetcore WebApp
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: myappplan
          is_linux: false
          sku: S1
          number_of_workers: 1
        frameworks:
          - name: "dotnetcore"
            version: "2.1"
```
### Any log messages given by the failure
>
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported framework dotnetcore for Windows web app."}`
### Expected/desired behavior
> Create the app service (this version is available via azure portal)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Container azure-cli + Mac Osx
### Versions
> Latest, Mojave

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.
